language: node_js
node_js:
  - "4.2"
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
  - SAUCE_USERNAME=flowjs
  - SAUCE_ACCESS_KEY=53e609a9-cb5d-4eac-a888-aa5419836f19
addons:
  sauce_connect: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma
  - npm install
script:
  - grunt karma:coverage
  - grunt karma:saucelabs || true
